[package]
name = "sabi-nes"
version = "0.1.0"
edition = "2018"
description = "A toy NES emulator"
authors = ["Dariusz Dajka <dariusz.dajka@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
