[package]
name = "sabi-nes"
version = "0.1.0"
edition = "2021"
description = "A toy NES emulator"
authors = ["Dariusz Dajka <dariusz.dajka@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
bitflags = "2.3.1"
clap = { version = "4.0.27", features = ["derive"] }
maplit = "1.0.2"
once_cell = "1.16.0"
sdl2 = "0.35.2"

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "1.3.0"
rand = "0.8.5"
