[package]
name = "sabi-nes"
version = "0.1.0"
edition = "2021"
description = "A toy NES emulator"
authors = ["Dariusz Dajka <dariusz.dajka@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
bitflags = "1.3.2"
lazy_static = "1.4.0"

[dev-dependencies]
assert_matches = "1.5.0"
rand = "0.8.4"
sdl2 = "0.35.1"