name: Rust

on:
  push:

jobs:
  check:
    runs-on: ubuntu-23.10
    steps:
      - uses: actions/checkout@v2
      - name: Check format
        run: cargo fmt -- --check
      - name: Cargo check
        run: cargo check

  build-and-test:
    runs-on: ubuntu-23.10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests and check examples
        run: cargo test --verbose

  clippy:
    runs-on: ubuntu-23.10
    steps:
      - uses: actions/checkout@v2
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings