name: Rust

on:
  push:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85.0
      - uses: actions-rs/cargo@v1
        name: Check formatting
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/cargo@v1
        name: Cargo check
        with:
          command: check

  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85.0
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --verbose
      - uses: actions-rs/cargo@v1
        name: Run tests and check examples
        with:
          command: test
          args: --verbose

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85.0
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        name: Run clippy
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings